### PR TITLE
Improved version with better fonts and logo

### PR DESCRIPTION
**Pull request by dietmarw**

### CODE REVIEW

**Comment by dietmarw** [comment]
@einhalv I'm wondering, do you still maintain this repo? Since it's been terrible silent.

**Comment by einhalv** [comment]
I don't really have time. If you want to take over, feel free!


Einar

________________________________

**Comment by dietmarw** [comment]
Sure. Simply give me the permissions.

**Comment by einhalv** [comment]
OK. I think I have given you admin rights now.


Einar


________________________________

**Comment by dietmarw** [comment]
Yes. Cheers.

**Pull request merged**
